xbmc/peripheral.joystick

peripheral.joystick/addon.xml, src/addon.cpp, src/api/Joystick.h, src/api/JoystickManager.h, src/api/directinput/JoystickInterfaceDirectInput.cpp
companion PR: https://github.com/garbear/xbmc/pull/23
=> changed: xbmc.peripheral -> kodi.peripheral

src/api/sdl/JoystickInterfaceSDL.cpp, src/api/sdl/JoystickSDL.h
=> fixed: SDL version mismatch

CMakeLists.txt
This was PRed and merged already into garbear/peripheral.joysticks :)
=> Fix defines

peripheral.joystick/resources/buttonmaps/xml/directinput/Generic_USB_Joystick_v121_p6_12b_1h_5a.xml, peripheral.joystick/resources/buttonmaps/xml/xinput/Xbox_360-compatible_controller_15b_6a.xml
Windows Xinput: Wired Xbox360 controller
Windows Directinput: PS Dualshock knockoff
=> Add 2 controller buttonmaps

peripheral.joystick/resources/buttonmaps/xml/linux/8Bitdo_NES30_GamePad_Joystick_22b_8a.xml, peripheral.joystick/resources/buttonmaps/xml/linux/8Bitdo_SFC30_GamePad_Joystick_22b_8a.xml
Keymaps for 8bitdo NES30 and SFC30 controllers in joystick mode.
=> Add NES30 and SFC30 keymaps

peripheral.joystick/resources/buttonmaps/xml/linux/NVIDIA_Corporation_NVIDIA_Controller_v01.03_14b_8a.xml
This adds a buttonmap for the controller shipped with Nvidia's Shield AndroidTV STB.
=> [buttonmap] Add buttonmap for Nvidia Shield Controller

peripheral.joystick/resources/buttonmaps/xml/linux/Dual_PSX-USB_Adaptor_Dual_PSX-USB_Adaptor_16b_4a.xml, peripheral.joystick/resources/buttonmaps/xml/linux/Logitech_Logitech_Dual_Action_12b_6a.xml, peripheral.joystick/resources/buttonmaps/xml/linux/Logitech_Logitech_RumblePad_2_USB_12b_6a.xml, peripheral.joystick/resources/buttonmaps/xml/linux/NVIDIA_Corporation_NVIDIA_Controller_v01.03_14b_8a.xml, peripheral.joystick/resources/buttonmaps/xml/linux/Xbox_360_Wireless_Receiver_15b_8a.xml
This fixes analogsticks in buttonmaps that already contain the n64 controller profile.
=> Analogstick fixes buttonmaps

peripheral.joystick/resources/buttonmaps/xml/android/Gamepad_v18D1_p2C40_11b_1h_6a.xml, peripheral.joystick/resources/buttonmaps/xml/android/NVIDIA_Corporation_NVIDIA_Controller_v01.03_v0955_p7210_11b_1h_6a.xml, src/filesystem/vfs/VFSFileUtils.cpp
The first commit fixes compiling on android and the other two commits add buttonmaps for Kodi for the Nexus Player and the NVidia Shield TV controllers.
=> Android support with two controller buttonmaps

peripheral.joystick/addon.xml.in, src/addon.cpp, src/api/Joystick.h, src/api/JoystickManager.h, src/api/JoystickTranslator.h, src/api/PeripheralScanner.cpp, src/filesystem/DirectoryCache.h, src/filesystem/DirectoryUtils.h, src/filesystem/IDirectoryUtils.h, src/storage/ButtonMapTranslator.h, src/storage/Device.h, src/storage/StorageManager.cpp, src/storage/StorageManager.h, src/utils/CommonIncludes.h
https://github.com/xbmc/xbmc/pull/9804 and https://github.com/xbmc/xbmc/pull/9671 for reference
addon.xml renaming and fix is to bring it up to par with other add-ons
=> Fix includes

peripheral.joystick/addon.xml.in, src/addon.cpp, src/api/Joystick.cpp, src/api/Joystick.h, src/api/JoystickManager.cpp, src/api/JoystickManager.h, src/api/xinput/JoystickInterfaceXInput.cpp, src/api/xinput/JoystickInterfaceXInput.h, src/api/xinput/JoystickXInput.cpp, src/api/xinput/JoystickXInput.h, src/storage/ButtonMapDefinitions.h, src/storage/ButtonMapTranslator.cpp, src/storage/xml/ButtonMapXml.cpp
Functionality needed for changes in https://github.com/xbmc/xbmc/pull/9663
=> Rumble and controller power off

peripheral.joystick/resources/settings.xml, src/api/Joystick.cpp, src/settings/Settings.cpp, src/settings/Settings.h
Deadzone settings are being moved to Kodi. Depends on https://github.com/xbmc/xbmc/pull/10309.
=> Remove deadzone setting

peripheral.joystick/resources/buttonmaps/xml/cocoa/Gamepad_F310_v046D_pC21D_15b_6a.xml, peripheral.joystick/resources/buttonmaps/xml/cocoa/Logitech_Dual_Action_v046D_pC216_12b_5a.xml, peripheral.joystick/resources/buttonmaps/xml/cocoa/Xbox_360_Wired_Controller_v046D_pC21D_15b_6a.xml, peripheral.joystick/resources/buttonmaps/xml/sdl/SDL_Game_Controller_15b_6a.xml
First round of button maps. I've got more coming
=> Buttonmaps

peripheral.joystick/addon.xml.in, src/addon.cpp, src/api/IJoystickInterface.h, src/api/JoystickManager.cpp, src/api/JoystickManager.h, src/api/udev/JoystickInterfaceUdev.h, src/api/xinput/JoystickInterfaceXInput.cpp, src/api/xinput/JoystickInterfaceXInput.h, src/api/xinput/XInputDLL.cpp, src/api/xinput/XInputDLL.h
Corresponds to https://github.com/xbmc/xbmc/pull/11707
=> Peripheral API v1.3.1 - Report rumble and power-off capabilities

src/api/sdl/JoystickSDL.cpp
=> [sdl] Fix hang when rescanning for joysticks

peripheral.joystick/addon.xml.in
=> Bump peripheral.joystick to v1.3.2 for SDL fix

src/addon.cpp
The for xbmc/xbmc#12011 needed addon changes.
=> Remove not used part

CMakeLists.txt, peripheral.joystick/addon.xml.in
Related to kodi Pull Request xbmc/xbmc#12029
Not merge in before is in Kodi!
=> change to automatic depends set on addon.xml

peripheral.joystick/addon.xml.in, src/addon.cpp
Related to Kodi pull request xbmc/xbmc#12109
=> remove no more needed version functions

peripheral.joystick/addon.xml.in
Version increase related to https://github.com/xbmc/xbmc/pull/12117
If you wish can I go a bit over the history and add a changelog there.
=> version increase after API way change

peripheral.joystick/addon.xml.in, src/addon.cpp
=> Update on kodi to addon interface

src/buttonmapper/ControllerTransformer.cpp, src/storage/JustABunchOfFiles.cpp
Minor fixes and improvements that I've been carrying in my `retroplayer` branch for one reason or another.
=> Minor fixes and improvements

src/api/xinput/JoystickInterfaceXInput.cpp, src/api/xinput/JoystickInterfaceXInput.h
This restores an updated version of the code originally added in 16c58c0 and removed in 37c1a28.
=> [xinput] Add motors to built-in button map

CMakeLists.txt, src/api/directinput/JoystickDirectInput.cpp, src/api/directinput/JoystickDirectInput.h, src/api/directinput/JoystickInterfaceDirectInput.cpp, src/api/xinput/XInputDLL.cpp, src/api/xinput/XInputDLL.h, src/utils/CommonIncludes.h, src/utils/windows/CharsetConverter.cpp, src/utils/windows/CharsetConverter.h
As title says. Thanks to @Paxxi for the hint.
=> Fix unicode build on Windows

peripheral.joystick/addon.xml.in, src/addon.cpp
Needed to have working if addon is disabled and enabled again
=> force set of settings after AddonCreate

CMakeLists.txt
=> [settings] Use "list" instead of "spinner" type

peripheral.joystick/resources/buttonmaps/xml/android/Xbox_Wireless_Controller_v045E_p02FD_11b_1h_6a.xml
=> [android] Add buttonmap for Xbox One S wireless controller

.travis.yml
=> .travis.yml: Update for addition of -DADDONS_DEFINITION_DIR

peripheral.joystick/addon.xml.in
* Adds language tags for `en_GB`
* Converts `<noicon>` and `<nofanart>` to `<assets>` tag
=> Updates for addon.xml.in

peripheral.joystick/resources/buttonmaps/xml/android/NVIDIA_Corporation_NVIDIA_Controller_v01.03_v0955_p7210_18b_8a.xml, peripheral.joystick/resources/buttonmaps/xml/android/OUYA_Game_Controller_v2836_p0001_18b_6a.xml
@garbear as discussed on Slack. I'll collect some more button maps and ping you when it's ready to merge
=> [android] add updated buttonmaps

peripheral.joystick/resources/buttonmaps/xml/android/virtual-remote_11b.xml
From https://github.com/xbmc/peripheral.joystick/pull/129#issuecomment-425123517 
thanks to @CiNcH83
=> [android] Add buttonmap for back button in Android TV Remote Control (again)

src/storage/xml/ButtonMapXml.cpp, src/storage/xml/ButtonMapXml.h
I've been carrying this patch since January but never got around to PR'ing it.
=> Remove unused parameter

peripheral.joystick/resources/buttonmaps/xml/android/Hi_keyboard_v0001_p0001_23b.xml, peripheral.joystick/resources/buttonmaps/xml/android/virtual-remote_23b.xml
fixes xbmc/xbmc#15372 and #159
thanks to @Gustav0ar and Ismadder1 (from the forum) for providing these buttonmaps
=> [Android] button maps for "Hi Keyboard" and "Android virtual remote"

docs/CONTRIBUTING.md
Created a small guide that covers some helpful ways to contribute.
=> Add contributing guide: CONTRIBUTING.md
