xbmc/peripheral.joystick

- CMakeLists.txt
- src/log/Log.cpp
I dont know much of the underlying build system and im also no expert on cmake so bear with me :)
Win doesn't have a syslog.h and i couldn't find one in msys so i had to disable these parts in the build for win. Interestingly enough there was already a check for HAVE_SYSLOG in Log.cpp but i couldn't find it being defined so i added a check in cmake and disabled the corresponding files.
ps: I didnt know if i should push here or to garbears repo. This here was more up to date so im pushing here.
ps2: Why exactly are you using a custom logging mechanism and not the kodi logging facilities?
> Fix syslog

- src/api/linux/JoystickInterfaceLinux.h
This should solve issue #6, which was missing a constructor implementation and crashing on load.
> Add missing constructor implemention.

- src/api/directinput/JoystickDirectInput.cpp
- src/api/directinput/JoystickDirectInput.h
- src/api/directinput/JoystickInterfaceDirectInput.cpp
- src/api/xinput/JoystickXInput.cpp
- src/api/xinput/JoystickXInput.h
This fixes the equality comparison for `CJoystickDirectInput` and `CJoystickXInput`. The problem is that comparing an initialized `CJoystick` object with an uninitialized one (as it is done when checking if a discovered joystick is already known) will always fail because the initialization alters the properties used in the comparison.
For `CJoystickDirectInput` we remember the GUID of the DirectInput device and use that one for the equality comparison.
For `CJoystickXInput` we simply compare the controller index (which is always a value between `0` and `3`).
> Fix equality comparison of classes derived from CJoystick 

- src/api/JoystickManager.cpp
- src/api/JoystickManager.h
- src/api/directinput/JoystickInterfaceDirectInput.cpp
- src/api/directinput/JoystickInterfaceDirectInput.h
- src/api/xinput/JoystickInterfaceXInput.h
The main part of this PR is the last commit which replaces the extremly slow detection of XInput devices enumerated by the DirectInput API using WMI with an implementation using the raw input API instead which is a lot faster. With this change I couldn't notice any hiccups/lag anymore when using my Xbox 360 Wireless Controller or my NES30 Bluetooth Controller.
Furthermore I've thrown in two cosmetic/cleanup commits and a commit that introduces a separate mutex/lock for `CJoystickManager::m_interfaces` to avoid abusing the lock that is meant for `CJoystickManager::m_joysticks` and to avoid destroying `CJoystickManager::m_interfaces` while it is being used.
> Fix DirectInput joystick interface causing hiccups/lag

- peripheral.joystick/resources/buttonmaps/xml/linux/Logitech_Logitech_RumblePad_2_USB_12b_6a.xml
- peripheral.joystick/resources/buttonmaps/xml/linux/Xbox_360_Wireless_Receiver_15b_6a.xml
Here are 2 button maps for Linux for the controllers I own.
They should be fairly close to the button positions on the respective original controllers (even if they have buttons with the same label but on a different position. For example on (A, B) on SNES are (B, A) on XBox 360.
> [buttonmap] Add XBox 360 Wireless and Logitech RumblePad 2 for Linux

- peripheral.joystick/resources/buttonmaps/xml/linux/PLAYSTATION_R_3_Controller.xml
Adds a buttonmap for Sony Playstation 3 controllers for Linux which is used when the controller is connected through Bluetooth with the sixaxis plugin in Bluez 5. With this buttonmap the controller works
out of the box in OpenELEC 6 (RetroPlayer test builds).
> [buttonmap] Add Sony PS3 map (connected through Bluez 5)

- CMakeLists.txt
- src/api/Joystick.cpp
- src/api/JoystickAsync.cpp
- src/api/JoystickAsync.h
- src/api/JoystickManager.cpp
- src/api/JoystickManager.h
- src/api/cocoa/JoystickInterfaceCocoa.h
- src/api/xinput/XInputDLL.h
- src/filesystem/DirectoryCache.cpp
- src/log/Log.cpp
- src/log/Log.h
- src/log/LogConsole.cpp
- src/log/LogConsole.h
- src/storage/ButtonMap.cpp
- src/storage/JustABunchOfFiles.cpp
- src/storage/JustABunchOfFiles.h
This fixes compilation after rename of platform to p8-platform in Pulse-Eight/platform#20.
I guess this breaks ABI and/or API, because of the namespace change.
> sync with platform rename to p8-platform Pulse-Eight/platform#20

- src/api/xinput/JoystickInterfaceXInput.h
- src/api/xinput/XInputDLL.cpp
- src/api/xinput/XInputDLL.h
This PR implements some additional XInput features which are not used / supported yet by the joystick API in general but I've tested reading the capabilities and battery info and turning the controller off works as well.
I also noticed that through `GetCapabilities()` we can check the type of the controller and that might actually be a lot of different things like a wheel, a guitar, a drum kit and what not. So maybe in the future we may have to extend the implementation to be able to handle the different controller types differently.
> extended XInput features

- src/utils/CommonIncludes.h
Well i have no clue what that stat64 didl does there - but in general we have all this stuff in p8-platform if i remember correct. Fact is - this is not good for darwin ;) (got an undefined struct __stat64 error during compilation)
I explicitly included that os-types.h for darwin only to fix compilation - other platform devs need to check if this is ok for them too and adapt accordingly.
> [ios] - fixed compilation due to struct __stat64 issues

- CMakeLists.txt
- peripheral.joystick/addon.xml.in
Needed after https://github.com/xbmc/xbmc/pull/9750 goes in
> [cmake] Rename find_package(kodi) to Kodi

- peripheral.joystick/addon.xml.in
- src/addon.cpp
- src/api/udev/JoystickInterfaceUdev.cpp
- src/buttonmapper/ControllerTransformer.cpp
- src/storage/ButtonMap.cpp
- src/storage/ButtonMap.h
- src/storage/IDatabase.h
- src/storage/JustABunchOfFiles.cpp
- src/storage/JustABunchOfFiles.h
- src/storage/StorageManager.cpp
- src/storage/StorageManager.h
- src/storage/api/DatabaseJoystickAPI.cpp
- src/storage/api/DatabaseJoystickAPI.h
- src/storage/xml/ButtonMapXml.cpp
This updates peripheral.joystick to add a separate API call to save button maps.
Corresponds to https://github.com/xbmc/xbmc/pull/10364
> Update to peripheral API v1.1.0: Add function to save button maps

- src/api/JoystickManager.cpp
Reports of some axes missing in udev driver (#52). Switch back to linux joystick API until this is fixed.
@MilhouseVM LibreELEC has already reverted to the linux driver, so that patch can be dropped
> Switch default provider from udev to linux

- src/api/directinput/JoystickDirectInput.cpp
- src/api/directinput/JoystickDirectInput.h
- src/api/directinput/JoystickInterfaceDirectInput.cpp
Trying to track down a crash in dinput8 I came across this and noticed we don't actually call Release on the input objects when we're done with them.
Not sure this solves the crash but at least we shouldn't be leaking resources anymore. Also added some extra safeguard around scanning for devices so that we ignore exclusive mode devices that we can't access anyway.
Also documentation says Acquire shall be called before calling Poll or basically anything else.
> [Fix] Resource leak

- src/api/directinput/JoystickDirectInput.cpp
- src/api/directinput/JoystickDirectInput.h
- src/api/directinput/JoystickInterfaceDirectInput.h
docs doesn't say anything about it
Also move callback out of class and hide it
in cpp file.
Setting this as __cdecl can cause stack corruption as the caller doesn't expect it.
> [FIX] Don't mark callback as __cdecl when

- src/api/directinput/JoystickDirectInput.cpp
- src/api/directinput/JoystickInterfaceDirectInput.cpp
This fixes a problem where joystick are discovered and then lost every five seconds.
Reported here: http://forum.kodi.tv/showthread.php?tid=295548&pid=2449281#pid2449281
> [directinput] Defer joystick acquisition to initialization

- CMakeLists.txt
- src/buttonmapper/ButtonMapUtils.cpp
- src/buttonmapper/ButtonMapUtils.h
- src/storage/ButtonMap.cpp
- src/storage/ButtonMap.h
When a feature is updated, it might conflict with an existing feature. Instead of erasing the existing feature, an attempt is made to update its primitives to the old feature being overwritten.
For example, if the button map is:
A -> 0
B -> 1
And the user maps "B -> 0", then the new button map will look like:
A -> 1
B -> 0
Here, instead of erasing the A (button 0) when it conflicts with the new B (also button 0), the A is updated to point to B's old button (1).
Part of https://github.com/xbmc/xbmc/pull/10630
> Fix loss of control if A becomes unmapped

- peripheral.joystick/resources/buttonmaps/xml/linux/Wireless_Controller_14b_18a.xml
This is the buttonmap for the PS4 controller when connected through Bluetooth. It is recognized as Wireless Controller. It maps all the buttons, except the trackpad in the middle which doesn't really match with anything on the "standard" controller shown on-screen in the controller configuration dialog anyway. However, it only has the mapping for the default game controller.
I can also provide the buttonmap for this PS4 controller from when it's connected through a USB cable. Then it's recognized as "Sony Computer Entertainment Wireless Controller". But I figured I'd do it one at a time. Although the only difference is the name attribute in the <device> tag and the filename.
> Added buttonmap for PS4 controller

- peripheral.joystick/resources/buttonmaps/xml/linux/Sony_Computer_Entertainment_Wireless_Controller_14b_18a.xml
This is the buttonmap for the PS4 controller when it's connected through USB. The mapping is entirely the same as when connected through Bluetooth, only the controller name is different. As with the Bluetooth mapping, this is only for the default game controller in Kodi and doesn't map the touchpad.
> Added buttonmap for PS4 controller (connected through USB)

- .travis.yml
- appveyor.yml
In https://github.com/xbmc/xbmc/pull/10446 the cmake folder was moved from `project` directory to the root directory.
> Fix Continuous Integration

- peripheral.joystick/resources/buttonmaps/xml/linux/8Bitdo_NES30_GamePad_16b_8a.xml
Adds support for the NES30 in normal "Joystick" mode, which is different from the currently supported NES30 in "PC Joystick" mode. [See the v2.52 firmware notes](http://www.nes30.com/firmware.html).
---
It appears in the latest firmware of the NES30 the device reports **16** buttons, not **22**. This allows XBMC to correctly identify it.
This also corrects the name of the device as it does not include `Joystick` in bluetooth mode.
I've never seen my NES30 report itself with the suffix `Joystick` in bluetooth mode. I am on Arch Linux however, maybe it reports differently on Windows and OSX. It's quite possible this device should have an alias added without the Joystick suffix. Pinging @N3MIS15 for information about his setup.
> Update NES30 buttonmap for latest firmware

- peripheral.joystick/resources/buttonmaps/xml/directinput/Twin_USB_Joystick_v0810_p0001_12b_1h_4a.xml
Add buttonmap for PS2 to usb converter.
Had some issues getting the buttonmap:
- This device can handle 2 controllers but kodi detects this as 1 entity.
- I can only map one action for the right stick, in Windows it's shown
as a trigger.
I added some screenshot/images of the device:
http://imgur.com/a/TxIpE
ping @Garbear
> Add PS2 converter buttonmap

- peripheral.joystick/resources/buttonmaps/xml/linux/Wireless_Controller_14b_8a.xml
I recently got the V2 version of the PS4 controller, released together with the PS4 Pro. It seems this one is recognized a little differently than the original version, though it's also recognized with the name "Wireless Controller". It seems to be recognized with 8 axes instead of 18 (maybe this makes it better compatible with udev?). I've created a buttonmap for it, which is available through this PR. It seems like both controllers work pretty well, even when connected at the same time. The actual contents of the buttonmap is exactly the same as for V1 of the PS4 controller, except for the axes count.
> Added buttonmap for PS4 V2 controller

- src/api/xinput/JoystickInterfaceXInput.cpp
- src/api/xinput/JoystickXInput.cpp
- src/api/xinput/XInputDLL.cpp
- src/api/xinput/XInputDLL.h
The crash on Windows 10:
```
INVALID_POINTER_READ_DETOURS_c0000005_XInputUap.dll!XInputCore::XInputManager::_XInputManager
```
This might be caused by the private API used to access the Guide button and Power-off feature. This PR disables these on Windows 10.
I can't compile on Windows ATM so this PR is untested.
> [xinput] Remove use of private APIs on Windows 8/10

- src/api/Joystick.cpp
- src/api/Joystick.h
- src/buttonmapper/ButtonMapTypes.h
- src/buttonmapper/ButtonMapUtils.cpp
- src/buttonmapper/ButtonMapUtils.h
- src/buttonmapper/ControllerTransformer.cpp
- src/buttonmapper/ControllerTransformer.h
This makes two improvements:
* It fires events for every discovered axis on every frame. Previously, continuous runs of the value 0.0 were elided. This gives the button mapper more data to work with.
*  Controller translation can now handle multi-feature relationships, like a D-pad (four buttons) representing an analog stick.
> Improvements to button mapping

- src/api/Joystick.cpp
- src/utils/StringUtils.cpp
- src/utils/StringUtils.h
Joystick drivers report all sorts of interesting names. Currently, if the name has trailing spaces, they are stripped before serializing.
Instead, we should serialize the full string, including trailing spaces, because
* Trimming spaces loses information
* RetroArch joystick configs include spaces
> Don't trim trailing space from joystick name

- debian/control
needed to fix ubuntu packaging
> [debian] add libudev-dev to build-deps

- CMakeLists.txt
I noticed that the Linux Joystick API driver was getting pulled in on Android
> [cmake] Disable linux and udev drivers on Android

- CMakeLists.txt
Error was:
```
[100%] Linking CXX shared library peripheral.joystick.dylib
Undefined symbols for architecture x86_64:
"_IOHIDDeviceCopyMatchingElements", referenced from:
JOYSTICK::CJoystickCocoa::Initialize() in JoystickCocoa.cpp.o
"_IOHIDDeviceGetProperty", referenced from:
JOYSTICK::CJoystickCocoa::Initialize() in JoystickCocoa.cpp.o
"_IOHIDElementGetDevice", referenced from:
JOYSTICK::CJoystickInterfaceCocoa::InputValueChanged(__IOHIDValue*) in JoystickInterfaceCocoa.cpp.o
"_IOHIDElementGetLogicalMax", referenced from:
JOYSTICK::CJoystickCocoa::Initialize() in JoystickCocoa.cpp.o
"_IOHIDElementGetLogicalMin", referenced from:
JOYSTICK::CJoystickCocoa::Initialize() in JoystickCocoa.cpp.o
"_IOHIDElementGetUsage", referenced from:
JOYSTICK::CJoystickCocoa::Initialize() in …
```
> Fix linking error on OSX

- src/storage/StorageUtils.cpp
Mainly to avoid conflicts when pigeonholing xml files into shorter names.
> Preserve underscores in file name

- CMakeLists.txt
- peripheral.joystick/addon.xml.in
- peripheral.joystick/resources/settings.xml.include
- src/settings/Settings.cpp
This fix the addon who comes with latest changes of Kodi to rework addons settings.
Further brings it the new settings.xml style (here my output):
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<settings version="1">
<section id="addon" label="-1">
<category id="main" label="30000">
<group id="1" label="0">
<setting id="driver_linux" type="integer" label="30001">
<default>0</default>
<constraints>
<options>
<option label="30005">0</option>
<option label="30007">1</option>
<option label="30002">2</option>
</options>
</constraints>
<control type="spinner" format="string"/>
</setting>
</group>
</category>
</section>
</settings>
```
> Fix settings

- src/api/directinput/JoystickDirectInput.cpp
- src/api/directinput/JoystickDirectInput.h
- src/api/directinput/JoystickInterfaceDirectInput.cpp
- src/api/xinput/JoystickInterfaceXInput.cpp
- src/api/xinput/XInputDLL.cpp
- TCHAR & TEXT identifiers don't start with an underscore
- updated to C++ based addon interface for window
@garbear @AlwinEsch FYI
> [fix] windows build failures

- CMakeLists.txt
This adds the header added in #112 to CMakeLists.txt.
> [cmake] Add missing header

- peripheral.joystick/addon.xml.in
- src/buttonmapper/ButtonMapUtils.cpp
- src/storage/ButtonMap.cpp
- src/storage/ButtonMap.h
- src/storage/StorageManager.cpp
- src/storage/StorageManager.h
- src/storage/xml/ButtonMapXml.cpp
- src/storage/xml/ButtonMapXml.h
- src/storage/xml/DatabaseXml.cpp
- src/storage/xml/DatabaseXml.h
This updates peripheral.joystick to handle serializing/deserializing relative pointers. Corresponds to https://github.com/xbmc/xbmc/pull/12556.
> [Peripheral API] Update to v1.3.4: relative pointer support

- src/addon.cpp
- src/addon.h
- src/api/PeripheralScanner.h
- src/storage/StorageManager.h
- src/utils/CommonMacros.h
And also fix some compiler warnings
> Fix compiler error

- peripheral.joystick/resources/buttonmaps/xml/android/virtual-remote_11b.xml
Report: https://forum.kodi.tv/showthread.php?tid=308480
Tested on Shield TV.
Android TV Remote Control:
> [android] Add buttonmap for back button in Android TV Remote Control

- peripheral.joystick/addon.xml.in
This bumps the version to v1.4.3 so that the backported buttonmaps in https://github.com/xbmc/peripheral.joystick/pull/131 have an up-to-date version to reference.
> Bump version to v1.4.3 to anchor backport of buttonmaps

- peripheral.joystick/addon.xml.in
- src/buttonmapper/ButtonMapUtils.cpp
- src/storage/xml/ButtonMapXml.cpp
This PR allows wheels and throttles to be mapped in the button mapper.
The buttonmap XML for wheels looks like:
```xml
<controller id="game.controller.saturn.arcade.racer">
<feature name="wheel">
<left axis="-0" />
<right axis="+0" />
</feature>
</controller>
```
The buttonmap XML for throttles looks like:
```xml
<controller id="game.controller.saturn.mission.stick">
<feature name="throttle">
<up axis="+3" />
<down axis="-3" />
</feature>
</controller>
```
For https://github.com/xbmc/xbmc/pull/13189.
> [Peripheral API] Update to v1.3.5: Wheel and throttle support

- CMakeLists.txt
- peripheral.joystick/addon.xml.in
- peripheral.joystick/resources/buttonmaps/xml/application/Mouse.xml
- src/api/JoystickTranslator.cpp
- src/api/JoystickTranslator.h
- src/buttonmapper/ButtonMapTranslator.cpp
- src/buttonmapper/ButtonMapUtils.cpp
- src/storage/Device.cpp
- src/storage/MouseTranslator.cpp
- src/storage/MouseTranslator.h
- src/storage/StorageUtils.cpp
- src/storage/xml/ButtonMapDefinitions.h
- src/storage/xml/ButtonMapXml.cpp
This PR allows mouse buttons and relative pointers to be stored in the buttonmap. An example buttonmap looks like:
```xml
<buttonmap>
<device name="Mouse" provider="application">
<controller id="game.controller.mouse">
<feature name="button4" mouse="button4" />
<feature name="button5" mouse="button5" />
<feature name="horizwheelleft" mouse="horizwheelleft" />
<feature name="horizwheelright" mouse="horizwheelright" />
<feature name="left" mouse="left" />
<feature name="middle" mouse="middle" />
<feature name="pointer">
<up axis="-y" />
<down axis="+y" />
<right axis="+x" />
<left axis="-x" />
</feature>
<feature name="right" mouse="right" />
<feature name="wheeldown" mouse="wheeldown" />
<feature name="wheelup" mouse="wheelup" />
</controller>
</device>
</buttonmap>
```
Corresponds to …
> Peripheral API v1.3.7: Mouse mapping support

- peripheral.joystick/resources/buttonmaps/xml/linux/Gamepad_17b_8a.xml
- peripheral.joystick/resources/buttonmaps/xml/linux/Microsoft_X-Box_360_pad_11b_8a.xml
Add support for WeTek Gamepad gaming controller: https://wetek.com/ww/en/product/gamepad.
The gamepad can work either via USB connection, or via Bluetooth. In each mode it gets identified differently: for cable connection - Microsoft_X-Box_360_pad_11b_8a (045E:028E), for Bluetooth - Gamepad_17b_8a (05AC:022D). Hence this PR provides two button maps to support both modes.
> linux: Add support for WeTek Gamepad

- peripheral.joystick/resources/buttonmaps/xml/linux/8Bitdo_NES30_Arcade_x__10b_8a.xml
- peripheral.joystick/resources/buttonmaps/xml/linux/Pro_Controller_16b_6a.xml
Added Nintendo Switch Pro Controller and 8bitdo NES30 Arcade Stick maps to Kodi. Configured basic map setup for Kodi and for NES, SNES, Sega Genesis controllers.
> Add NDO SW Pro Controller and 8bitdo NES30 Arcade

- peripheral.joystick/resources/buttonmaps/xml/cocoa/Wireless_360_Controller_v045E_p028E_15b_6a.xml
I went through the controller mapping dialog and, for every controller, found a button map I had made in a kodi-game add-on. The button map summarizes the libretro core, so this button map contains the physical mapping of a controller to every profile.
This enables instant-config in the controller dialog, because once the user maps their controller, the button mapper will use this data as a rosetta stone to map all future controllers.
As a result, this buttonmap becomes the authoritative libretro mapping, and all other controllers only need to be mapped to a single profile. This reduces the size of the database. It also lets us map e.g. SNES controllers to the SNES profile, which we can use in the player manager to figure out what to show the user for the controller in their hands.
> [cocoa] Add libretro mappings for all controllers

- CMakeLists.txt
- src/buttonmapper/ButtonMapTypes.h
- src/buttonmapper/ControllerTransformer.cpp
- src/buttonmapper/ControllerTransformer.h
- src/buttonmapper/StringRegistry.cpp
- src/buttonmapper/StringRegistry.h
Switch from strings to int handles now that button maps (like https://github.com/xbmc/peripheral.joystick/pull/146) can contain over 60 controller profiles.
The transformation map storage is O(N<sup>2</sup>) in the number of profiles, so the large profile will thrash memory.
> Optimize controller transformer memory usage

- peripheral.joystick/resources/buttonmaps/xml/android/NVIDIA_Corporation_NVIDIA_Controller_v01.04_v0955_p7214_18b_8a.xml
Button layout is the same as the older Shield controller in https://github.com/xbmc/peripheral.joystick/pull/151, so I copied the XML and changed the name and USB product ID. It should work.
Android actually maps pretty much every controller for its input API, so in the future we'll be able to use Android button mapping data to zero-config almost all controllers.
> [Android] Add buttonmap for newer Shield controller

- peripheral.joystick/addon.xml.in
[45 commits](https://github.com/xbmc/peripheral.joystick/compare/v1.4.6...master) to master since v1.4.6. Let's bump the version for Leia.
> addon.xml.in: Bump to version 1.4.7 for Leia release
